"""Interface-facing facade for runtime composition helpers."""

from __future__ import annotations

from micro_model_agent.dataset.infrastructure.runtime import (
    build_dataset_export_workflow,
    build_dataset_merge_workflow,
    build_dataset_relabel_workflow,
    build_dataset_synthesis_workflow,
    build_dataset_validation_workflow,
    build_jsonl_dataset_example_store,
    build_trace_dataset_export_workflow,
    build_trace_review_workflow,
)
from micro_model_agent.evaluation.infrastructure.runtime import (
    build_evaluation_comparison_workflow,
    build_synthetic_evaluation_workflow,
    build_trace_evaluation_workflow,
    build_workspace_staged_evaluation_workflow,
    build_workspace_staged_review_workflow,
    default_evaluation_available_tools,
)
from micro_model_agent.execution.infrastructure.agents_runtime import build_static_coding_workflow
from micro_model_agent.execution.infrastructure.composition import (
    build_coding_workflow,
    build_event_pipeline,
)
from micro_model_agent.execution.infrastructure.models.runtime import (
    ConfiguredToolLoopResult,
    EvaluationModelSelection,
    RuntimeModelOptions,
    base_model_from_adapter,
    build_loop_model_provider,
    build_model_provider,
    loop_budget_response,
    path_config_value,
    path_env,
    path_or_none,
    resolve_mcp_model_settings,
    resolve_model_options,
    run_cli_tool_loop,
    run_configured_tool_loop,
    run_mcp_agent_loop,
    runtime_model_metadata,
    select_evaluation_model,
    string_config_value,
    tool_prompt_schemas,
)
from micro_model_agent.execution.infrastructure.persistence_runtime import (
    DEFAULT_TRACE_DIR,
    append_comparison_trace_event,
    comparison_trace_store,
    register_workspace_record,
    registered_workspace_path,
    review_comparison_trace_session,
    start_comparison_trace_session,
    stop_comparison_trace_session,
    trace_dir,
    workflow_trace_record,
    workflow_trace_store,
    workspace_registry,
)
from micro_model_agent.promotion.infrastructure.runtime import (
    build_promotion_gate_workflow,
    build_promotion_list_workflow,
    build_promotion_package_ollama_workflow,
    build_promotion_record_workflow,
    build_promotion_select_workflow,
)
from micro_model_agent.repository_ops.infrastructure.runtime import (
    initialize_local_repository,
    local_repository_initialized,
    write_local_repository_index,
)
from micro_model_agent.repository_ops.infrastructure.tools_runtime import (
    PatchPolicyToolExecutor,
    allowed_test_commands,
    build_builtin_tool_executor,
    builtin_tool_exists,
    builtin_tool_names,
    builtin_tool_summaries,
    builtin_tools_response,
    execute_builtin_tool_request,
)
from micro_model_agent.training.infrastructure.runtime import build_synthetic_training_workflow

__all__ = [
    "ConfiguredToolLoopResult",
    "DEFAULT_TRACE_DIR",
    "EvaluationModelSelection",
    "PatchPolicyToolExecutor",
    "RuntimeModelOptions",
    "allowed_test_commands",
    "append_comparison_trace_event",
    "base_model_from_adapter",
    "build_builtin_tool_executor",
    "build_coding_workflow",
    "build_dataset_export_workflow",
    "build_dataset_merge_workflow",
    "build_dataset_relabel_workflow",
    "build_dataset_synthesis_workflow",
    "build_dataset_validation_workflow",
    "build_evaluation_comparison_workflow",
    "build_event_pipeline",
    "build_jsonl_dataset_example_store",
    "build_loop_model_provider",
    "build_model_provider",
    "build_promotion_gate_workflow",
    "build_promotion_list_workflow",
    "build_promotion_package_ollama_workflow",
    "build_promotion_record_workflow",
    "build_promotion_select_workflow",
    "build_static_coding_workflow",
    "build_synthetic_evaluation_workflow",
    "build_synthetic_training_workflow",
    "build_trace_dataset_export_workflow",
    "build_trace_evaluation_workflow",
    "build_trace_review_workflow",
    "build_workspace_staged_evaluation_workflow",
    "build_workspace_staged_review_workflow",
    "builtin_tool_exists",
    "builtin_tool_names",
    "builtin_tool_summaries",
    "builtin_tools_response",
    "comparison_trace_store",
    "default_evaluation_available_tools",
    "execute_builtin_tool_request",
    "initialize_local_repository",
    "local_repository_initialized",
    "loop_budget_response",
    "path_config_value",
    "path_env",
    "path_or_none",
    "register_workspace_record",
    "registered_workspace_path",
    "resolve_mcp_model_settings",
    "resolve_model_options",
    "review_comparison_trace_session",
    "run_cli_tool_loop",
    "run_configured_tool_loop",
    "run_mcp_agent_loop",
    "runtime_model_metadata",
    "select_evaluation_model",
    "start_comparison_trace_session",
    "stop_comparison_trace_session",
    "string_config_value",
    "tool_prompt_schemas",
    "trace_dir",
    "workflow_trace_record",
    "workflow_trace_store",
    "workspace_registry",
    "write_local_repository_index",
]
